### ISSUE TITLE
Loot Window Anchor wrong (32:9)

### ISSUE THREAD

**Issue by NikolaiThingnesLeira** [Jademalo/SurroundFix#1]
First off, thanks for a great addon that looks like it could fix a great many issues with my interface panels!

So far I've noticed a couple of issues, for reference I'm running a 49" 32:9 Ultrawide.
With the auto settings it gets up to a 16:9 Aspect Ratio for center screen, which works nicely for interface panels like Character, vendor etc. However my loot window when attched to my mouse pointer shows up in the wrong spot.

![image](https://user-images.githubusercontent.com/8503265/97359043-74e40f00-189c-11eb-952c-2bcbdc4b26c1.png)

There also seems to some issues with embedding to interface panels with Addonskins and ElvUI, where the addons believe the frame is to the far right, altough this is a minor issue which I fixed by doing a temporary `/sfix aspect 32:9` and reverting back to 16:9.

**Comment by NikolaiThingnesLeira** [comment]
And the embed setting:
![image](https://user-images.githubusercontent.com/8503265/97361376-b88c4800-189f-11eb-932a-243b3b18cefd.png)

**Comment by Jademalo** [comment]
No problem, happy it's useful!

This is the bug that I mention in the Readme, unfortunately there's nothing I can actually do about this.

For whatever reason, there are a number of addons that don't handle their frames correctly, using absolute screen coordinates instead of coordinates relative to UIParent.
Proper practice is to anchor everything relative to UIParent, and this is the behavior that the default UI uses. My addon simply resizes UIParent, so if an addon doesn't use it correctly it can result in this behaviour.

Ultimately this isn't an issue with my addon, nor is it something that I'm even able to fix. Your best bet is opening a ticket for the specific addons that are behaving weirdly, and hoping they'll fix it. Let me know if you open a ticket for any of them, and I'll try to add some detail there.

Sorry! :(

**Comment by NikolaiThingnesLeira** [comment]
You're completely right, I tested it without addons enabled now and it works then. I'll open an issue with them instead. Have a nice (insert greeting relative to your timezone)!
